name: update
on:
  schedule:
      - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  update:
    name: update
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run update
        run: bash update.sh

      - name: show git diff
        run: git diff HEAD

      - name: Exit early if no meaningful changes
        run: |
          git diff --exit-code -I'"version":' -I'"log_list_timestamp":' -I'kCTExpirationTime' -- ':(exclude)*.sig' && echo "Changes found." || exit 0
          git add .
          DATE=$(date -u "+%Y-%m-%d %H:%M:%S UTC")
          git commit -m "Automated update: ${DATE}"
          git push origin HEAD:main
